camunda:
  taskpool:
    engine-eventing:
      enabled: true
    collector:
      tasklist-url: http://localhost:8080/tasklist/
      enricher:
        application-name: ${spring.application.name}  # default
        type: processVariables
      sender:
        enabled: true
        type: tx
    dataentry:
      sender:
        enabled: true
        type: simple
