sourceDirs:
  - './../../../../datapool/datapool-api/src/main/kotlin'
  - './../../../../datapool/datapool-core/src/main/kotlin'
  - './../../../../engine/camunda-engine-client/src/main/kotlin'
  - './../../../../engine/datapool-collector/src/main/kotlin'
  - './../../../../engine/taskpool-collector/src/main/kotlin'
  - './../../../../engine/taskpool-engine-springboot-starter/src/main/kotlin'
  - './../../../../engine/variable-serializer/src/main/kotlin'
  - './../../../../taskpool/taskpool-api/src/main/kotlin'
  - './../../../../taskpool/taskpool-core/src/main/kotlin'
  - './../../../../view/view-api/src/main/kotlin'
  - './../../../../view/simple/src/main/kotlin'
  - './../../../../view/mongo/src/main/kotlin'

classPages:
  menu:
    - type: 'separator'
      title: 'Class Info'
      order: 100
    - type: 'kotlindocClassLinks'
      includeItems: true
      order: 110
