sections:
  introduction:
    title: Introduction
    key: introduction
    order: 100
  user-guide:
    key: user-guide
    title: User Guide
    order: 200
  developer-guide:
    key: developer-guide
    title: Developer Guide
    order: 300

introduction:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested
    - type: 'separator'
      title: 'Introduction'
      order: 1000
    - type: 'wiki'
      section: introduction
      order: 1010

user-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested
    - type: 'separator'
      title: 'User Guide'
      order: 1000
    - type: 'wiki'
      section: user-guide
      order: 1010

developer-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested
    - type: 'separator'
      title: 'Developer Guide'
      order: 1000
    - type: 'wiki'
      section: developer-guide
      order: 1010

wikiPages:
  layout: geopattern2

defaultConfig:
  createPdf: true
