sections:
  'introduction':
    title: 'Introduction'
    order: 100
  'developer-guide':
    title: 'Developer Guide'
    order: 200

wikiPages:
  layout: geopattern2

'introduction':
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested
    - type: 'separator'
      title: 'Introduction'
      order: 1000
    - type: 'wiki'
      section: 'introduction'
      order: 1010
'developer-guide':
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested

defaultConfig:
  createPdf: true
