---
engines:
  duplications:
    exclude_paths:
      - "**/src/test/kotlin/**"
exclude_paths:
  - ".github/ISSUE_TEMPLATE/**"
  - "examples/components/tasklist-angular/**"
  - "examples/components/process-forms/**"
  - "docs/**"
