server:
  port: 8081

spring:
  application:
    name: taskpool
#  datasource:
#    url: jdbc:h2:tcp://localhost:9092/mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    generate-ddl: false
#    hibernate.ddl-auto: validate
#    show-sql: false
#    open-in-view: false
#  flyway:
#    enabled: true
#    locations: "classpath:db/migrations"

camunda:
  taskpool:
    task-url-resolver:
      defaultTaskTemplate: "tasks/${formKey}/id/${id}"
      defaultApplicationTemplate: "http://localhost:8080/${applicationName}"

logging.level.io.holunda.camunda.taskpool:
  core: WARN
  view.simple: WARN
  example.tasklist: WARN


swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Taskpool Application
    description: Rest interface of the example taskpool application.
  dockets:
    tasklist:
      basePackage: "io.holunda.camunda.taskpool.example.tasklist"
      path: "/**"
      apiInfo:
        title: Tasklist Application
        description: Rest interface of the task list.
    cockpit:
      basePackage: "io.holunda.camunda.taskpool.cockpit"
      path: "/**"
      apiInfo:
        title: Taskpool Cockpit
        description: Rest interface of the cockpit.

