server:
  port: 8081

spring:
  application:
    name: taskpool

camunda:
  taskpool:
    task-url-resolver:
      defaultTaskTemplate: "tasks/${formKey}/id/${id}"
      defaultApplicationTemplate: "http://localhost:8080/${applicationName}"

logging.level.io.holunda.camunda.taskpool:
  core: WARN
  view.simple: WARN
  example.tasklist: WARN


swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Taskpool Application
    description: Rest interface of the example taskpool application.
  dockets:
    tasklist:
      basePackage: "io.holunda.camunda.taskpool.example.tasklist"
      path: "/**"
      apiInfo:
        title: Tasklist Application
        description: Rest interface of the task list.
