server:
  port: 8081

spring:
  application:
    name: taskpool

camunda:
  taskpool:
    form-url-resolver:
      defaultTaskTemplate: "tasks/${formKey}/id/${id}"
      defaultProcessTemplate: "${processDefinitionKey}/${formKey}"
      defaultApplicationTemplate: "http://localhost:8080/${applicationName}"
      applications:
        example-process-approval:
          url: "http://localhost:8080/example-process-approval"
          processes:
            process_approve_request: "start"


logging.level.io.holunda.camunda.taskpool:
  core: WARN
  view.simple: INFO
  example.tasklist: WARN


swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Taskpool Application
    description: Rest interface of the example taskpool application.
  dockets:
    tasklist:
      basePackage: "io.holunda.camunda.taskpool.example.tasklist"
      path: "/**"
      apiInfo:
        title: Tasklist Application
        description: Rest interface of the task list.
