site:
  about:
    siteName: Camunda BPM Taskpool
    siteDescription: A component for pooling Camunda BPM user tasks with business data for high performance queries.
    avatar: 'assets/media/holunda.png'

theme:
  useSidebarSearch: true
  primaryColor: '#DE0000'
  extraCss:
    - 'assets/css/asciidoc-admonitionblock.scss'
  social:
    twitter: 'holisticon'
    github: 'holunda-io/camunda-bpm-taskpool'
  menu:
    - type: 'page'
      itemId: 'quick-start'
      title: 'Quick Start'

    - type: 'wikiSections'
    - type: 'submenu'
      title: 'Explore'
      menu:
      - type: 'page'
        title: 'Changelog'
        itemId: 'changelog'
      - type: 'page'
        title: 'License'
        itemId: 'license'


allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'kotlin'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'


services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'zambrovski'
        repo: 'holunda-io/camunda-bpm-taskpool'
