site:
  about:
    siteName: Camunda BPM Taskpool
    siteDescription: A component for pooling Camunda BPM user tasks with business data for high performance queries.
    avatar: 'assets/media/holunda.png'

theme:
  useSidebarSearch: true
  primaryColor: '#DE0000'
  extraCss:
    - 'assets/css/asciidoc-admonitionblock.scss'
  social:
    twitter: 'holisticon'
    github: 'holunda-io/camunda-bpm-taskpool'
  menu:
    - type: 'page'
      itemId: 'quick-start'
      title: 'Quick Start'

    - type: 'wikiSections'

    - type: 'submenu'
      title: 'User Manual'
      itemId: 'Introduction'


allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'kotlin'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'


changelog:
  includeMinorVersions: true
  includeReleaseNotes: true

wiki:
  defaultConfig:
    createPdf: true

kotlindoc:
  sourceDirs:
    - './../../../../datapool/datapool-api/src/main/kotlin'
    - './../../../../datapool/datapool-core/src/main/kotlin'
    - './../../../../engine/camunda-engine-client/src/main/kotlin'
    - './../../../../engine/camunda-engine-plugin/src/main/kotlin'
    - './../../../../engine/datapool-collector/src/main/kotlin'
    - './../../../../engine/taskpool-collector/src/main/kotlin'
    - './../../../../engine/taskpool-engine-springboot-starter/src/main/kotlin'
    - './../../../../engine/variable-serializer/src/main/kotlin'
    - './../../../../taskpool/taskpool-api/src/main/kotlin'
    - './../../../../taskpool/taskpool-core/src/main/kotlin'
    - './../../../../view/view-api/src/main/kotlin'
    - './../../../../view/simple/src/main/kotlin'
    - './../../../../view/mongo/src/main/kotlin'


services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'zambrovski'
        repo: 'holunda-io/camunda-bpm-taskpool'
