useSidebarSearch: true
showVersion: false
legacySearch: false
primaryColor: '#16480c'
trianglifyOptions:
  x_colors: ['#000', '#16480c', '#000']
extraCss:
  - 'assets/css/menu.scss'
  - 'assets/css/asciidoc-admonitionblock.scss'
social:
  twitter: 'holisticon'
  github: 'holunda-io/camunda-bpm-taskpool'
  other:
    - link: 'https://www.holunda.io/camunda-bpm-taskpool/'
      label: 'Home'
      icon: 'fas fa-home'
  slack:
    - link: 'https://holunda.slack.com/messages/taskpool/'
      label: 'Slack'
      icon: 'fas fa-slack'
menu:
  - type: 'submenu'
    title: 'Introduction'
    menu:
      - type: 'wiki'
        section: 'introduction'
  - type: 'submenu'
    title: 'User Guide'
    icon: 'fas fa-home'
    menu:
      - type: 'wiki'
        section: 'user-guide'
  - type: 'submenu'
    title: 'Developer Guide'
    menu:
      - type: 'wiki'
        section: 'developer-guide'
  - type: 'submenu'
    title: 'Explore'
    menu:
      - type: 'page'
        title: 'Changelog'
        itemId: 'Changelog'
      - type: 'page'
        title: 'License'
        itemId: 'License'
      - type: 'page'
        title: 'Project Readme'
        itemId: 'Readme'
