site_name: Polyflow
theme: readthedocs
nav:
  - 'Home': index.md
  - 'Introduction':
    - 'Motivation': introduction/motivation.md
    - 'Features': introduction/features.md
    - 'Solution Architecture': introduction/solution-architecture.md
    - 'Further Outlook': introduction/further-outlook.md
  - 'Integration Guide': integration/index.md
  - 'Reference Guide':
    - 'Overview': reference-guide/components/index.md
    - 'Process Engine Integration Components':
      - 'Camunda BPM Engine Interaction Client': reference-guide/components/camunda-interaction-client.md
      - 'Camunda BPM Engine Taskpool Collector': reference-guide/components/camunda-taskpool-collector.md
      - 'Camunda BPM Engine Taskpool SpringBoot Starter': reference-guide/components/camunda-starter.md
      - 'Taskpool Sender': reference-guide/components/common-taskpool-sender.md
      - 'Datapool Sender': reference-guide/components/common-datapool-sender.md
    - 'Core Components':
      - 'Taskpool Core': reference-guide/components/core-taskpool.md
      - 'Datapool Core': reference-guide/components/core-datapool.md
    - 'View Components':
      - 'In-Memory View': reference-guide/components/view-simple.md
      - 'Mongo DB View': reference-guide/components/view-mongo.md
    - 'Other Components':
      - 'Form URL Resolver': reference-guide/components/other-form-url-resolver.md
      - 'Tasklist URL Resolver': reference-guide/components/other-tasklist-url-resolver.md
      - 'Variable Serializer': reference-guide/components/other-variable-serializer.md
  - 'Example Application':
    - 'Overview': examples/example-application.md
    - 'Example Components':
      - 'Example Components Overview': examples/example-components/index.md
      - 'Process Application Frontend': examples/example-components/pa-frontend.md
      - 'Process Application Backend': examples/example-components/pa-backend.md
      - 'User Management': examples/example-components/user-management.md
      - 'Process Platform Frontend': examples/example-components/pp-frontend.md
      - 'Process Platform Backend': examples/example-components/pp-backend.md
    - 'Distribution Scenarios':
      - 'Scenarios Overview': examples/scenarios/index.md
      - 'Single Node': examples/scenarios/single-node.md
      - 'Distributed using Axon Server': examples/scenarios/distributed-axon-server.md
      - 'Distributed without Axon Server': examples/scenarios/distributed-no-axon-server.md
  - 'Developer Guide':
    - 'Contribution': developer-guide/contribution.md
    - 'Project Setup': developer-guide/project-setup.md

plugins:
  - search
  - git-committers:
      repository: holunda-io/camunda-bpm-taskpool
      branch: master
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
