server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    history-level: activity
    id-generator: simple
    database:
      schema-update: false
      type: h2
  taskpool:
    engine:
      eventing:
        enabled: true
    collector:
      enricher:
        type: processVariables
      sender:
        enabled: true

logging.level.io.holunda.camunda.taskpool:
  sender: WARN
  core: WARN
  view.simple: DEBUG


swagger:
  enabled: true
  redirect: true
  apiInfo:
    title: Example Process application
    description: REST interface of the example process application.
  dockets:
    rest:
      basePackage: "io.holunda.camunda.taskpool.example.process.rest"
      path: "/**"
