server:
  port: 8080

spring:
  application:
    name: example-process-approval
  datasource:
    url: jdbc:postgresql://localhost:5432/process
    username: process_user
    password: S3Cr3T!
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    history-level: full
    id-generator: strong
    database:
      schema-update: false
      type: postgres
    webapp:
      index-redirect-enabled: false
  taskpool:
    engine-eventing:
        enabled: true
    collector:
      tasklist-url: http://localhost:8081/tasklist/
      process:
        enabled: true
      enricher:
        application-name: ${spring.application.name}  # default
        type: processVariables
      sender:
        enabled: true
        type: tx
    dataentry:
      sender:
        enabled: true
        type: simple

<<<<<<< Updated upstream
logging.level.io.holunda.camunda.taskpool:
  sender: DEBUG
  core: WARN
  view.simple: DEBUG

=======
logging.level:
  io.holunda.camunda:
    taskpool:
      sender: DEBUG
      core: WARN
      view.simple: DEBUG
    datapool:
      sender: DEBUG
  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
>>>>>>> Stashed changes

swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Process Application
    description: REST interface of the example process application.
  dockets:
    process:
      basePackage: "io.holunda.camunda.taskpool.example.process.rest"
      path: "/**"

