server:
  port: 8080

spring:
  application:
    name: example-process-approval
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    history-level: full
    id-generator: strong
    database:
      schema-update: false
      type: h2
    webapp:
      index-redirect-enabled: false
  taskpool:
    engine-eventing:
        enabled: true
    collector:
      tasklist-url: http://localhost:8081/tasklist/
      enricher:
        application-name: ${spring.application.name}  # default
        type: processVariables
      sender:
        enabled: true
        type: tx
    dataentry:
      sender:
        enabled: true
        type: simple

logging.level.io.holunda.camunda.taskpool:
  sender: DEBUG
  core: WARN
  view.simple: DEBUG


swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Process Application
    description: REST interface of the example process application.
  dockets:
    process:
      basePackage: "io.holunda.camunda.taskpool.example.process.rest"
      path: "/**"

