server:
  port: 8080

spring:
  application:
    name: example-process-approval
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    history-level: activity
    id-generator: strong
    database:
      schema-update: false
      type: h2
  taskpool:
    engine-eventing:
        enabled: true
    collector:
      enricher:
        application-name: ${spring.application.name}  # default
        type: processVariables
      sender:
        enabled: true
        type: simple
    dataentry:
      sender:
        enabled: true
        type: simple
    url-resolver:
      default: "id/\\${task.id}"
      tasks:
        foo: "forms/\\${task.formKey}/id/\\${task.id}"

logging.level.io.holunda.camunda.taskpool:
  sender: WARN
  core: WARN
  view.simple: DEBUG


swagger:
  enabled: true
  redirect: false
  apiInfo:
    title: Example Process Application
    description: REST interface of the example process application.
  dockets:
    process:
      basePackage: "io.holunda.camunda.taskpool.example.process.rest"
      path: "/**"
    webflux:
      basePackage: "io.holunda.camunda.taskpool.example.process.webflux"
      path: "/**"
    tasklist:
      basePackage: "io.holunda.camunda.taskpool.example.tasklist"
      path: "/**"
      apiInfo:
        title: Tasklist Application
        description: REST interface of the process task list.

