swagger: '2.0'
info:
  title: Example Process REST API
  version: 0.0.1
  description: API for the example approval process.
basePath: '/example-process-approval/rest/'
tags:
- name: Request
  description: Operations to manipulate requests.
- name: User Task Amend Request
  description: Operations on task amend request.
- name: User Task Approve Request
  description: Operations on task approve request.

schemes:
- http
- https
paths:
  '/environment':
    get:
      tags:
        - Environment
      summary: Retrieives information about the environment.
      operationId: getEnvironment
      responses:
        200:
          schema:
            $ref: '#/definitions/Environment'

  '/request':
    post:
      tags:
        - Request
      summary: Create a new approval request draft and starts approval process.
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
        - in: body
          name: request
          description: Request to be approved.
          required: true
          schema:
            $ref: '#/definitions/ApprovalRequestDraft'
      operationId: startNewApproval
      responses:
        201:
          description: Sucessful operation.

  '/request/{id}':
    get:
      tags:
        - Request
      summary: Loads request for specified id.
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
        - in: path
          name: id
          type: string
          description: Request id.
          required: true
      operationId: getApprovalRequest
      responses:
        200:
          description: Sucessful operation.
          schema:
            title: Approval Request.
            $ref: '#/definitions/ApprovalRequest'

  '/approve-request/id/{id}':
    get:
      tags:
        - User Task Approve Request
      summary: Retrieves information about the task approve request with specified id.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          description: Task id.
          required: true
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
      operationId: loadTaskApproveRequestFormData
      responses:
        200:
          description: Sucessful operation.
          schema:
            title: Approve task data.
            $ref: '#/definitions/TaskApproveRequestFormData'
    post:
      tags:
        - User Task Approve Request
      summary: Receives form data for the completion of the task approve request with specified id.
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          description: Task id.
          required: true
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
        - in: body
          name: payload
          description: Payload to be added to the process instance on task completion.
          schema:
            $ref: '#/definitions/TaskApproveRequestSubmitData'
      operationId: submitTaskApproveRequestSubmitData
      responses:
        201:
          description: Sucessful operation.

  '/amend-request/id/{id}':
    get:
      tags:
        - User Task Amend Request
      summary: Retrieves information about the task amend request with specified id.
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          description: Task id.
          required: true
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
      operationId: loadTaskAmendRequestFormData
      responses:
        200:
          description: Sucessful operation.
          schema:
            title: Amend task data.
            $ref: '#/definitions/TaskAmendRequestFormData'
    post:
      tags:
        - User Task Amend Request
      summary: Receives form data for the completion of the task amend request with specified id.
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          type: string
          description: Task id.
          required: true
        - in: header
          name: X-Current-User-ID
          description: Specifies the id of current user.
          type: string
          required: true
        - in: body
          name: payload
          description: Payload to be added to the process instance on task completion.
          schema:
            $ref: '#/definitions/TaskAmendRequestSubmitData'
      operationId: submitTaskAmendRequestSubmitData
      responses:
        201:
          description: Sucessful operation.

definitions:
  Task:
    type: object
    properties:
      id:
        type: string
        description: Id of the user task.
      name:
        type: string
        description: Action to execute.
      description:
        type: string
        description: Description of the user task.
      formKey:
        type: string
        description: Form key of the task (as defined in the process model).
      assignee:
        type: string
        description: User name of assigned user.
      createTime:
        type: string
        description: Creation date and time of the task.
        format: date-time
      dueDate:
        type: string
        description: Due date and time of the task.
        format: date-time
      followUpDate:
        type: string
        description: Follow-up date and time of the task.
        format: date-time
      priority:
        type: integer
        description: Priority of the task.
    required:
    - id
    - name
    - description
    - createTime
    - dueDate
    - businessKey

  ApprovalRequestDraft:
    type: object
    properties:
      amount:
        type: string
        format: int
      currency:
        type: string
      subject:
        type: string
      applicant:
        type: string
    required:
      - applicant
      - subject
      - amount
      - currency

  ApprovalRequest:
    type: object
    properties:
      id:
        type: string
      subject:
        type: string
      applicant:
        type: string
      amount:
        type: string
        format: int
      currency:
        type: string
    required:
      - id
      - applicant
      - subject
      - amount
      - currency

  TaskApproveRequestFormData:
    type: object
    properties:
      task:
        $ref: '#/definitions/Task'
      approvalRequest:
        $ref: '#/definitions/ApprovalRequest'
    required:
      - task
      - approvalRequest

  TaskAmendRequestFormData:
    type: object
    properties:
      task:
        $ref: '#/definitions/Task'
      approvalRequest:
        $ref: '#/definitions/ApprovalRequest'
      comment:
        type: string
        description: Comment of the approver.
    required:
      - task
      - approvalRequest

  TaskApproveRequestSubmitData:
    type: object
    properties:
      decision:
        type: string
        description: One of 'APPROVE', 'REJECT' or 'RETURN' denoting the decition of the approver.
      comment:
        type: string
        description: Optional comment.
    required:
      - decision

  TaskAmendRequestSubmitData:
    type: object
    properties:
      action:
        type: string
        description: One of 'CANCEL' or 'RESUBMIT' actions reflecting the decision of the originator, how to proceed with the request.
      approvalRequest:
        $ref: '#/definitions/ApprovalRequest'
        description: Optional changed approval request.
      comment:
        type: string
        description: Optional comment.
    required:
      - action

  Environment:
    type: object
    properties:
      applicationName:
        type: string
        description: Name of this process application.
      tasklistUrl:
        type: string
        description: URL of the tasklist.
