site:
  about:
    siteName: Camunda BPM Taskpool
    siteDescription: skdfjh skdjfh ksfj
BsDoc:
  primaryColor: '#DE9149'
  social:
    twitter: 'holisticon'
    github: 'holunda-io/camunda-bpm-taskpool'
  menu:
    - type: 'wiki'

#services:
#  publications:
#    stages:
#      - type: 'githubPages'
#        username: 'zambrovski'
#        repo: 'holunda-io/camunda-bpm-taskpool'
