server:
  port: 8080
spring:
  application:
    name: example-process-approval
  datasource:
    url: jdbc:postgresql://localhost:5432/process
    username: process_user
    password: S3Cr3T!
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"
  groovy:
    template:
      check-template-location: false

#axon.serializer:
#  general: jackson
#  events: jackson
#  messages: jackson

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    history-level: full
    id-generator: strong
    database:
      schema-update: false
      type: postgres
    webapp:
      index-redirect-enabled: false
  taskpool:
    gateway:
      type: revision-aware
      revision-aware:
        default-query-timeout: 3
    collector:
      tasklist-url: http://localhost:8081/taskpool/
      application-name: ${spring.application.name}  # default
      send-commands-enabled: true
      task:
        enabled: true
        enricher:
          type: processVariablesSimpleDataEntryCommandSenderTest
        sender:
          type: tx
      process-definition:
        enabled: true
      process-instance:
        enabled: true
    dataentry:
      sender:
        enabled: true
        type: simpleSimpleDataEntryCommandSenderTest
        applicationName: ${spring.application.name}  # default
    form-url-resolver:
      defaultTaskTemplate:  "/tasks/${formKey}/${id}?userId=%userId%"
      defaultApplicationTemplate: "http://localhost:${server.port}/${applicatioName}"
      defaultProcessTemplate: "/${formKey}?userId=%userId%"

logging.level:
  io.holunda.camunda:
    taskpool:
      gateway: DEBUG
      sender: INFO
      core: WARN
      view.simple: INFO
    datapool:
      sender: INFO
  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
