name: Java CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: ['1.8', '11.0.5']
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Build with Maven
        run: ./mvnw clean verify -U -B
      - name: Run ITests with Maven
        run: ./mvnw integration-test failsafe:verify -Pitest -DskipFrontend -B

  codecov:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          yml: ./codecov.yml #optional
